spring:
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/dict
    username: springboot
    password: springboot
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.data.jpa: DEBUG
    org.hibernate: DEBUG
